# See https://pre-commit.com for more information
fail_fast: false
exclude: ^build/
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
        files: ^src/
      - id: check-added-large-files
  - repo: https://github.com/pocc/pre-commit-hooks
    rev: python
    hooks:
      - id: clang-format
        files: ^src/
      - id: clang-tidy
        files: ^src/
